import { Link } from "react-router-dom";
import Header from "./Header";

export default function PredictiveMaintenanceDashboard() {
  return (
    <div id="predictive-maintenance-dashboard-page" className="page">
      <Header />
      <div id="content-wrapper-2">
        <div class="content">
          <div class="content-block">
            <h2 class="content-block-title">
              DRONE PREDICTIVE MAINTENANCE APP
            </h2>
            <p class="content-block-description">
              <b>Client:</b> Rhoman Aerospace
            </p>
            <p class="content-block-description">
              <b>Role:</b> AWS Solutions Architect / Project Lead
            </p>
            <p class="content-block-description">
              <b>Goal:</b> Build a full stack web app to store and analyze drone
              flight data
            </p>
          </div>
          <div class="content-block">
            <img
              class="content-block-image"
              id="dashboard-diagram"
              src="./dashboard-diagram.png"
              width="100%"
            />
          </div>
          <div class="content-block">
            <p class="content-block-description">
              In the summer of 2021, I interned for a drone start-up that needed
              to store information generated by its fleet to optimize their
              control system. I envisioned a database that automatically
              received data from drones and a python script that infers their
              engines' health using machine learning.
            </p>
          </div>
        </div>

        <div class="content-block">
          <p class="content-block-description">
            <b>Components:</b>
          </p>
          <ul>
            <li>
              Database: AWS DynamoDB stores drone specs; S3 stores flight logs
            </li>
            <li>
              AI: Python script that is hosted on an EC2 and a Flask server.
            </li>
            <li>React Web App: Enables viewing logs and running inference.</li>
          </ul>
        </div>
        <div class="content-block">
          <p class="content-block-description">
            I collaborated with a hardware engineer to enable a Raspberry Pi to
            register drone specs and send telemetry to S3. I worked with an
            artificial intelligence engineer to pull that data and generate a
            plot with predicted values. To showcase our work, we built a web app
            that shows the data and enables users to run inference and display
            results.
          </p>
        </div>
        <div class="content-block">
          <img
            class="content-block-image"
            id="dashboard-web-app"
            src="./dashboard-web-app.png"
            width="100%"
          />
        </div>
        <div class="content-block">
          <h2 class="content-block-shout">
            The project was continued for development as the company's first
            minimum viable product.
          </h2>
          <p class="content-block-description">
            Because it would be offered to clients, it had to enable them to
            upload and download their logs. Multiple clients would share the
            same AWS database. It had to be secure from public access.
          </p>
          <p class="content-block-description">
            I leveraged Amplify and Cognito to protect the app with login. When
            a user uploaded a file, it would create a tag in DynamoDB that would
            have the user's cognitoID as a field and the filename as the primary
            key. When they logged in, they would only see filenames that they
            had access to.
          </p>
        </div>
        <div class="content-block">
          <img
            class="content-block-image"
            id="dashboard-web-app"
            src="./flight-log-data-transfer-diagram.png"
            width="100%"
          />
        </div>
        <div class="content-block">
          <img
            class="content-block-image"
            id="dashboard-web-app"
            src="./query-by-tag-er-diagram.png"
            width="100%"
          />
        </div>
      </div>
      <div className="footer">
        <Link className="page-link bottom-nav" to={`/`}>
          <p className="content-block-button">return to main</p>
        </Link>
      </div>
    </div>
  );
}
